export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export const Constants = {
  public: {
    Enums: {
      activity_type_enum: [
        "1:1",
        "Pairs",
        "Small Group",
        "Whole Class",
        "Stations",
        "Clubs",
      ],
      billing_enum: ["Hourly", "Fixed", "Retainer"],
      bloom_enum: [
        "Remember",
        "Understand",
        "Apply",
        "Analyze",
        "Evaluate",
        "Create",
      ],
      category_enum: ["Lesson Planning", "Engagement", "Assessment"],
      class_status: ["active", "completed", "upcoming", "archived"],
      content_type_enum: [
        "blog",
        "case_study",
        "research",
        "research_question",
        "teaching_technique",
        "activity",
        "tutorial",
        "diary_entry",
        "event",
        "service",
        "about",
      ],
      delivery_type_enum: ["In-class", "Online", "Live", "Homework"],
      enrollment_status: ["enrolled", "completed", "dropped", "pending"],
      event_mode_enum: ["Online", "In-person", "Hybrid", "Live"],
      event_price_type_enum: ["Free", "Paid"],
      event_status_enum: ["Upcoming", "Before", "During", "After", "Follow-Up"],
      event_type_enum: ["Workshop", "Webinar", "Meetup"],
      filter_type_enum: [
        "Edu Tech",
        "Tutorials",
        "Teaching Techniques",
        "Class Activity",
        "Teacher Reflection",
        "Tips",
        "Shop",
        "Case Study",
        "Research",
        "Teacher Debates",
      ],
      instruction_type_enum: [
        "Direct Instruction",
        "Differentiated Instruction",
        "Inquiry-Based Learning",
        "Project-Based Learning",
        "Problem-Based Learning",
        "Play-Based Learning",
        "Game-Based Learning",
        "Gamification",
        "Cooperative Learning",
        "Experiential Learning",
        "Design Thinking",
        "Socratic Seminar",
        "Station Rotation",
        "Blended Learning",
      ],
      language_level_enum: ["A1", "A2", "B1", "B2", "C1", "C2"],
      page_enum: [
        "research_blog",
        "edutech",
        "teacher_diary",
        "events",
        "services",
        "about",
      ],
      payment_enum: ["Free", "Paid", "Education Discount"],
      platform_enum: [
        "Mobile App",
        "Webapp",
        "Smartphone",
        "Smartboard",
        "Mac",
        "Windows",
      ],
      resource_type_enum: [
        "Worksheets",
        "Printables",
        "Task Cards",
        "Flashcards",
        "Mats",
        "Slides",
        "Presentations",
        "Videos",
        "Animations",
        "Pictures",
        "Posters",
        "Readers",
        "eBooks",
        "Audio",
        "Podcasts",
        "Quizzes",
        "Interactive Activities",
        "Labs",
        "Experiments",
        "Simulations",
        "Coding Challenges",
        "Spreadsheets",
      ],
      service_model_enum: ["1:1", "Whole Staff PD", "Audit", "Custom"],
      sla_tier_enum: ["Basic", "Standard", "Pro", "Enterprise"],
      stage_enum: [
        "Early Childhood",
        "Pre-K",
        "Kindergarten",
        "Primary",
        "Secondary",
        "High School",
        "K-12",
        "K-5",
      ],
      subcategory_enum: [
        "Lesson Planning",
        "Lesson Delivery",
        "Engagement",
        "Evaluation",
      ],
      subject_enum: [
        "Phonics",
        "English",
        "Math",
        "Science",
        "Biology",
        "Chemistry",
        "Physics",
        "Earth Science",
        "History",
        "Geography",
        "Music",
        "Arts",
        "ICT",
        "PE",
        "Global Perspective",
        "Circle Time",
        "Break Time",
        "STEAM",
      ],
      user_role_enum: ["Teacher", "Admin", "Parent", "Student", "Other"],
    },
  },
} as const;

export type PublicEnums = {
  [Key in keyof typeof Constants.public.Enums]:
    (typeof Constants.public.Enums)[Key][number];
};
