-- Insert localized Albanian blog content
INSERT INTO public.content_master
  (page, content_type, filter_type, language, title, subtitle, slug, category, stage, subject, tags, is_published, published_at, excerpt, content)
VALUES
  ('edutech', 'blog', 'Edu Tech', 'sq',
   'Risitë EdTech në klasat shqiptare',
   'Si mundësitë digjitale po fuqizojnë mësuesit',
   'risite-edtech-shqip-sq',
   'Engagement', 'Secondary', 'ICT', ARRAY['teknologji', 'arsim', 'shqip'],
   true, now(),
   'Një përmbledhje e mjeteve të reja teknologjike që po ndryshojnë përvojën mësimore në Shqipëri.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Ky artikull përmbledh mënyrat se si platformat e reja shqiptare po mbështesin mësuesit me mjete intuitive dhe përkthime automatike."}}]}'::jsonb),
  ('edutech', 'tutorial', 'Tutorials', 'sq',
   'Udhëzues hap-pas-hapi për Google Classroom',
   'Konfigurimi i klasës suaj virtuale në 15 minuta',
   'google-classroom-udhezues-sq',
   'Lesson Planning', 'K-12', 'ICT', ARRAY['google classroom', 'udhezues', 'digjital'],
   true, now(),
   'Mësoni si të krijoni detyra dhe të organizoni nxënësit në Google Classroom në gjuhën shqipe.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Nga krijimi i kursit te publikimi i materialeve, ky udhëzues tregon çdo hap me terma në shqip për të ndihmuar kolegët që sapo po nisin me mësimin online."}}]}'::jsonb),
  ('research_blog', 'teaching_technique', 'Teaching Techniques', 'sq',
   'Teknika bashkëpunuese për orët e letërsisë',
   'Si të nxisni diskutime të thella mes nxënësve',
   'teknika-bashkepunuese-sq',
   'Lesson Planning', 'Secondary', 'English', ARRAY['bashkepunim', 'diskutim', 'letersi'],
   true, now(),
   'Strategji praktike për të strukturuar punën në grupe dhe analiza teksti në gjuhën shqipe.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Artikulli përshkruan teknika të thjeshta për të organizuar role të qarta, pyetje të hapura dhe rubrika vlerësimi që përfshijnë çdo nxënës në diskutim."}}]}'::jsonb),
  ('edutech', 'activity', 'Class Activity', 'sq',
   'Stacione leximi për klasat fillore',
   'Një aktivitet i gjallë për të gjithë nxënësit',
   'aktivitet-stacion-leximi-sq',
   'Engagement', 'Primary', 'English', ARRAY['lexim', 'stacione', 'aktivitet'],
   true, now(),
   'Organizoni një qarkullim stacionesh leximi me detyra të niveluara në shqip.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Mësuesit gjejnë udhëzime për të krijuar stacione me tekste të ndryshme, karta fjalori dhe ushtrime të shpejta reflektimi për të mbështetur lexuesit fillestarë."}}]}'::jsonb),
  ('teacher_diary', 'diary_entry', 'Teacher Reflection', 'sq',
   'Reflektim: Java ime e parë me mësimin hibrid',
   'Balancimi i nxënësve në klasë dhe online',
   'reflektim-hibrid-sq',
   'Lesson Planning', 'High School', 'Science', ARRAY['reflektim', 'hibrid', 'mësim'],
   true, now(),
   'Një rrëfim personal mbi sfidat dhe sukseset e javës së parë me modelin hibrid.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Ditari shpjegon si u menaxhua komunikimi me nxënësit në klasë dhe online, cilat mjete funksionuan më mirë dhe çfarë do të ndryshojë javën e ardhshme."}}]}'::jsonb),
  ('teacher_diary', 'blog', 'Tips', 'sq',
   'Këshilla të shpejta për menaxhimin e kohës në klasë',
   'Tre rutina që e mbajnë orën në ritëm',
   'keshilla-menaxhim-kohe-sq',
   'Lesson Planning', 'K-12', NULL, ARRAY['keshilla', 'organizim', 'kohe'],
   true, now(),
   'Zbuloni rutina të thjeshta që ndihmojnë mësuesit të ruajnë fokusin dhe energjinë gjatë orës.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Nga agjenda vizuale te sinjalet kohore, këto tre praktika ofrojnë qartësi për nxënësit dhe hapësirë për reflektim të shpejtë në fund të çdo ore."}}]}'::jsonb),
  ('edutech', 'blog', 'Shop', 'sq',
   'Pako burimesh STEM në shqip',
   'Materiale të gatshme për eksperimente praktike',
   'paketa-stem-shqip-sq',
   'Assessment', 'K-5', 'STEAM', ARRAY['stem', 'materiale', 'shqip'],
   true, now(),
   'Një përzgjedhje aktivitetesh dhe posterash të përkthyer për të mbështetur mësimin e shkencës në gjuhën shqipe.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Lista përfshin eksperimente të thjeshta me udhëzime në shqip, tabela për matje dhe postera ngjyrash që shpjegojnë hapat shkencorë për nxënësit e vegjël."}}]}'::jsonb),
  ('research_blog', 'case_study', 'Case Study', 'sq',
   'Studim rasti: Laboratori mobil në gjimnazin e Tiranës',
   'Çfarë mësuam nga një program pilot gjashtëmujor',
   'studim-rasti-laborator-sq',
   'Assessment', 'Secondary', 'Science', ARRAY['studim rasti', 'laborator', 'shkencë'],
   true, now(),
   'Një analizë e rezultateve dhe reagimeve të mësuesve pas vendosjes së një laboratori mobil.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Raporti ndan të dhëna mbi frekuentimin, projektet e nxënësve dhe mënyrën si ekipet e shkollës përshtatën oraret për të përdorur laboratorin lëvizës."}}]}'::jsonb),
  ('research_blog', 'research', 'Research', 'sq',
   'Kërkim: Projekti bazuar në probleme rrit motivimin',
   'Vëzhgime nga tre shkolla të mesme',
   'kerkimi-projekteve-sq',
   'Assessment', 'Secondary', 'Math', ARRAY['kerkime', 'motivim', 'projekti'],
   true, now(),
   'Rezultatet tregojnë rritje të angazhimit kur lëndët e matematikës lidhen me sfida reale.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Studimi vlerësoi ditarët e nxënësve dhe matjet e pjesëmarrjes, duke treguar se problemet me kontekst lokal e bëjnë matematikën më të kuptueshme."}}]}'::jsonb),
  ('teacher_diary', 'blog', 'Teacher Debates', 'sq',
   'Debat mes mësuesve: A lejohet celulari në klasë?',
   'Argumente pro dhe kundër nga kolegët',
   'debat-celulari-klase-sq',
   'Engagement', 'High School', 'Global Perspective', ARRAY['debat', 'celular', 'rregulla'],
   true, now(),
   'Mësues nga shkolla të ndryshme ndajnë përvojat e tyre për përdorimin e telefonit gjatë orës.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Artikulli sjell shembuj të politikave të ndryshme dhe sugjeron mënyra për ta kthyer pajisjen në mjet mësimor kur vendosen rregulla të qarta."}}]}'::jsonb);

-- Insert localized Vietnamese blog content
INSERT INTO public.content_master
  (page, content_type, filter_type, language, title, subtitle, slug, category, stage, subject, tags, is_published, published_at, excerpt, content)
VALUES
  ('edutech', 'blog', 'Edu Tech', 'vi',
   'Xu hướng EdTech trong lớp học Việt Nam',
   'Công cụ số giúp giáo viên dẫn dắt bài học sinh động',
   'xu-huong-edtech-vi',
   'Engagement', 'Secondary', 'ICT', ARRAY['cong nghe', 'giao duc', 'viet nam'],
   true, now(),
   'Tổng hợp những nền tảng mới đang hỗ trợ giáo viên Việt Nam xây dựng bài học hấp dẫn.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Bài viết giới thiệu các ứng dụng cung cấp giao diện tiếng Việt, tự động chấm điểm và phân tích mức độ tham gia của học sinh."}}]}'::jsonb),
  ('edutech', 'tutorial', 'Tutorials', 'vi',
   'Hướng dẫn từng bước Google Classroom',
   'Thiết lập lớp học trực tuyến chỉ trong 15 phút',
   'huong-dan-google-classroom-vi',
   'Lesson Planning', 'K-12', 'ICT', ARRAY['google classroom', 'huong dan', 'truc tuyen'],
   true, now(),
   'Học cách tạo bài tập, giao nộp và phản hồi cho học sinh bằng tiếng Việt.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Từ việc tạo lớp đến tổ chức chủ đề, hướng dẫn giúp giáo viên mới dễ dàng quản lý tài liệu và thông báo rõ ràng cho học sinh."}}]}'::jsonb),
  ('research_blog', 'teaching_technique', 'Teaching Techniques', 'vi',
   'Chiến thuật hợp tác cho giờ Văn',
   'Tạo diễn đàn thảo luận sâu và cởi mở',
   'chien-thuat-hop-tac-vi',
   'Lesson Planning', 'Secondary', 'English', ARRAY['hop tac', 'thao luan', 'ngu van'],
   true, now(),
   'Các bước cụ thể để phân vai, đặt câu hỏi mở và đánh giá nhóm bằng tiếng Việt.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Chiến thuật đề xuất sử dụng bảng mục tiêu, vai trò người dẫn và người tổng hợp để mọi học sinh đều có tiếng nói trong buổi thảo luận."}}]}'::jsonb),
  ('edutech', 'activity', 'Class Activity', 'vi',
   'Hoạt động trạm đọc cho tiểu học',
   'Vòng quay nhiệm vụ giúp học sinh hào hứng',
   'hoat-dong-tram-doc-vi',
   'Engagement', 'Primary', 'English', ARRAY['tram doc', 'tieu hoc', 'hoat dong'],
   true, now(),
   'Thiết kế các trạm đọc với trò chơi từ vựng và góc ghi chú bằng tiếng Việt.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Giáo viên được gợi ý cách chuẩn bị thẻ từ, câu hỏi hiểu bài và góc nghe đọc để hỗ trợ nhiều mức độ năng lực."}}]}'::jsonb),
  ('teacher_diary', 'diary_entry', 'Teacher Reflection', 'vi',
   'Suy ngẫm: Tuần đầu với lớp học kết hợp',
   'Giữ nhịp giữa học sinh trực tiếp và trực tuyến',
   'suy-ngam-lop-ket-hop-vi',
   'Lesson Planning', 'High School', 'Science', ARRAY['suy ngam', 'ket hop', 'kinh nghiem'],
   true, now(),
   'Nhật ký chia sẻ bài học rút ra sau tuần đầu áp dụng mô hình hybrid.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Tác giả mô tả cách phân bổ thời gian, sử dụng bảng nhiệm vụ và phản hồi nhanh để tạo cảm giác kết nối cho cả hai nhóm học sinh."}}]}'::jsonb),
  ('teacher_diary', 'blog', 'Tips', 'vi',
   'Mẹo quản lý thời gian trên lớp',
   'Ba thói quen giữ tiết học đúng tiến độ',
   'meo-quan-ly-thoi-gian-vi',
   'Lesson Planning', 'K-12', NULL, ARRAY['meo day hoc', 'quan ly', 'thoi gian'],
   true, now(),
   'Những gợi ý nhanh giúp giáo viên duy trì sự tập trung và chuyển hoạt động mượt mà.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Áp dụng tín hiệu âm thanh, bảng quy trình và phút tĩnh lặng cuối giờ để học sinh tự đánh giá tiến độ của mình."}}]}'::jsonb),
  ('edutech', 'blog', 'Shop', 'vi',
   'Gói tài nguyên STEM tiếng Việt',
   'Dụng cụ và poster sẵn sàng cho thí nghiệm nhỏ',
   'goi-tai-nguyen-stem-vi',
   'Assessment', 'K-5', 'STEAM', ARRAY['stem', 'tai nguyen', 'poster'],
   true, now(),
   'Bộ sưu tập hoạt động dịch sang tiếng Việt giúp giáo viên tổ chức giờ khoa học thú vị.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Gói bao gồm hướng dẫn từng bước, bảng kết quả và biểu đồ màu giúp học sinh ghi lại khám phá khoa học."}}]}'::jsonb),
  ('research_blog', 'case_study', 'Case Study', 'vi',
   'Nghiên cứu tình huống: Phòng thí nghiệm lưu động',
   'Bài học từ chương trình thử nghiệm sáu tháng',
   'nghien-cuu-tinh-huong-phong-thi-nghiem-vi',
   'Assessment', 'Secondary', 'Science', ARRAY['tinh huong', 'thi nghiem', 'trai nghiem'],
   true, now(),
   'Phân tích kết quả và phản hồi của giáo viên khi triển khai phòng thí nghiệm di động.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Số liệu cho thấy tỉ lệ tham gia tăng, học sinh chủ động đề xuất đề tài mới và giáo viên điều chỉnh thời gian thực hành hiệu quả hơn."}}]}'::jsonb),
  ('research_blog', 'research', 'Research', 'vi',
   'Nghiên cứu: Dạy học theo dự án nâng động lực',
   'Quan sát từ ba trường trung học',
   'nghien-cuu-du-an-vi',
   'Assessment', 'Secondary', 'Math', ARRAY['nghien cuu', 'dong luc', 'du an'],
   true, now(),
   'Kết quả chỉ ra mức độ tham gia tăng rõ rệt khi bài toán gắn với bối cảnh thực tế.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Nhóm nghiên cứu phân tích bảng theo dõi tiến trình và nhật ký học sinh để chứng minh tầm quan trọng của nhiệm vụ mang tính cộng đồng."}}]}'::jsonb),
  ('teacher_diary', 'blog', 'Teacher Debates', 'vi',
   'Tranh luận giáo viên: Có nên cho dùng điện thoại?',
   'Chia sẻ góc nhìn từ nhiều trường khác nhau',
   'tranh-luan-dien-thoai-lop-hoc-vi',
   'Engagement', 'High School', 'Global Perspective', ARRAY['tranh luan', 'dien thoai', 'quy tac'],
   true, now(),
   'Giáo viên trình bày lợi ích và rủi ro khi cho phép học sinh mang điện thoại vào lớp.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Bài viết gợi ý các điều kiện và hoạt động giúp biến thiết bị thành công cụ học tập, đồng thời giữ an toàn số cho học sinh."}}]}'::jsonb);
