-- Drop unused metadata columns from content_master
ALTER TABLE public.content_master
  DROP COLUMN IF EXISTS age_grade,
  DROP COLUMN IF EXISTS audience,
  DROP COLUMN IF EXISTS billing,
  DROP COLUMN IF EXISTS bloom_level,
  DROP COLUMN IF EXISTS case_study_tags,
  DROP COLUMN IF EXISTS currency,
  DROP COLUMN IF EXISTS curriculum_alignment,
  DROP COLUMN IF EXISTS data_compliance,
  DROP COLUMN IF EXISTS deliverables,
  DROP COLUMN IF EXISTS device_os,
  DROP COLUMN IF EXISTS diary_type,
  DROP COLUMN IF EXISTS engagement_features,
  DROP COLUMN IF EXISTS event_status,
  DROP COLUMN IF EXISTS faq_json,
  DROP COLUMN IF EXISTS file_format,
  DROP COLUMN IF EXISTS forum_category,
  DROP COLUMN IF EXISTS guarantee,
  DROP COLUMN IF EXISTS idea_tips,
  DROP COLUMN IF EXISTS language_level,
  DROP COLUMN IF EXISTS learning_goals,
  DROP COLUMN IF EXISTS license,
  DROP COLUMN IF EXISTS login_method,
  DROP COLUMN IF EXISTS materials_devices,
  DROP COLUMN IF EXISTS mood,
  DROP COLUMN IF EXISTS newsletter_segment,
  DROP COLUMN IF EXISTS prep_level,
  DROP COLUMN IF EXISTS research_question_tags,
  DROP COLUMN IF EXISTS research_type,
  DROP COLUMN IF EXISTS resource_type,
  DROP COLUMN IF EXISTS service_model,
  DROP COLUMN IF EXISTS sla_tier,
  DROP COLUMN IF EXISTS standards_other,
  DROP COLUMN IF EXISTS testimonials_json,
  DROP COLUMN IF EXISTS translation_of,
  DROP COLUMN IF EXISTS view_count;

-- Drop indexes that referenced removed columns
DROP INDEX IF EXISTS idx_content_event;
