-- Seed additional multilingual test blog posts for verification
INSERT INTO public.content_master
  (page, content_type, filter_type, language, title, subtitle, slug, category, stage, subject,
   tags, is_published, published_at, excerpt, content, read_time, author)
VALUES
  -- English test blog posts
  ('research_blog', 'blog', 'Teaching Techniques', 'en',
   'Test Post: Inquiry Warm-Ups that Spark Curiosity',
   'Quick prompts to get learners talking in the first five minutes',
   'test-inquiry-warm-ups-en',
   'Engagement', 'Primary', 'Science', ARRAY['inquiry', 'warm-up', 'test'],
   true, now(),
   'A set of fast inquiry routines teachers can trial to start science lessons with energy.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Try a question-of-the-day board, quick pair predictions, and student-lead explanations to kickstart observation skills."}}]}'::jsonb,
   4,
   '{"name": "SchooltechHub Team"}'::jsonb),
  ('edutech', 'blog', 'Edu Tech', 'en',
   'Test Post: Tracking Progress with Simple Dashboards',
   'Free tools that visualize formative assessment data in minutes',
   'test-progress-dashboards-en',
   'Assessment', 'K-12', 'ICT', ARRAY['dashboards', 'data', 'test'],
   true, now(),
   'Highlights of three dashboard templates educators can pilot with their next quiz export.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Explore spreadsheet add-ons, no-code chart builders, and tips for sharing quick wins with families."}}]}'::jsonb,
   5,
   '{"name": "SchooltechHub Team"}'::jsonb),
  -- Albanian test blog posts
  ('research_blog', 'blog', 'Teaching Techniques', 'sq',
   'Post Test: Pyetje nxitëse për të nisur orën e shkencës',
   'Tre rutina të shpejta që ndezin kuriozitetin e nxënësve',
   'post-test-pyetje-shkence-sq',
   'Engagement', 'Primary', 'Science', ARRAY['pyetje', 'kuriozitet', 'test'],
   true, now(),
   'Përshkrim i shkurtër i aktiviteteve të hapjes që ndihmojnë nxënësit të diskutojnë idetë e tyre.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Filloni me karta pyetjesh, çiftime të shpejta për të krahasuar hipoteza dhe një tabelë reflektimi me post-it."}}]}'::jsonb,
   4,
   '{"name": "SchooltechHub"}'::jsonb),
  ('edutech', 'blog', 'Edu Tech', 'sq',
   'Post Test: Monitorimi i progresit me tabela vizuale',
   'Mjete falas që tregojnë rezultatet në kohë reale',
   'post-test-monitorim-progresi-sq',
   'Assessment', 'K-12', 'ICT', ARRAY['tabela', 'teknologji', 'test'],
   true, now(),
   'Tre modele tabelash që mësuesit mund t’i provojnë për të paraqitur të dhënat e kuizeve.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Artikulli thekson përdorimin e Google Sheets, grafikëve automatike dhe ndarjen e rezultateve me prindërit."}}]}'::jsonb,
   5,
   '{"name": "SchooltechHub"}'::jsonb),
  -- Vietnamese test blog posts
  ('research_blog', 'blog', 'Teaching Techniques', 'vi',
   'Bài test: Hoạt động khởi động khơi gợi tò mò',
   'Câu hỏi nhanh giúp học sinh sẵn sàng quan sát',
   'bai-test-khoi-dong-to-mo-vi',
   'Engagement', 'Primary', 'Science', ARRAY['cau hoi', 'khoi dong', 'test'],
   true, now(),
   'Gợi ý các hoạt động mở đầu ngắn giúp lớp học khoa học trở nên sôi nổi.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Thử áp dụng bảng dự đoán, câu hỏi đố nhanh và phần chia sẻ mini để học sinh tự kết nối trải nghiệm."}}]}'::jsonb,
   4,
   '{"name": "SchooltechHub"}'::jsonb),
  ('edutech', 'blog', 'Edu Tech', 'vi',
   'Bài test: Theo dõi tiến độ bằng bảng điều khiển đơn giản',
   'Công cụ miễn phí trực quan hóa dữ liệu đánh giá',
   'bai-test-bang-dieu-khien-vi',
   'Assessment', 'K-12', 'ICT', ARRAY['bang dieu khien', 'du lieu', 'test'],
   true, now(),
   'Giới thiệu ba mẫu bảng điều khiển giáo viên có thể thử ngay sau bài kiểm tra.',
   '{"blocks": [{"type": "paragraph", "data": {"text": "Bài viết nêu mẹo xuất dữ liệu, chọn biểu đồ phù hợp và chia sẻ kết quả với phụ huynh."}}]}'::jsonb,
   5,
   '{"name": "SchooltechHub"}'::jsonb);
