-- Insert sample blog posts
INSERT INTO public.blogs (
  title, 
  slug, 
  excerpt, 
  content,
  author,
  author_image,
  featured_image,
  tags,
  keywords,
  meta_title,
  meta_description,
  category,
  is_published,
  published_at,
  view_count,
  read_time
) VALUES 
(
  'Innovative Teaching Techniques for STEM Education',
  'innovative-teaching-techniques-stem',
  'Discover cutting-edge methods to make STEM subjects more engaging and accessible for students of all ages.',
  '{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "STEM education is evolving rapidly, and teachers need new approaches to keep students engaged. This article explores innovative techniques that have proven successful in classrooms worldwide."}]}]}',
  '{"name": "Dr. Sarah Johnson", "bio": "Education researcher and STEM advocate"}',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
  'https://images.unsplash.com/photo-1522202176988-66273c2fd55f',
  ARRAY['STEM', 'Innovation', 'Teaching Methods'],
  ARRAY['STEM education', 'teaching techniques', 'innovation'],
  'Innovative Teaching Techniques for STEM Education',
  'Learn about cutting-edge methods to make STEM subjects more engaging for students',
  'Teaching Techniques',
  true,
  NOW() - INTERVAL '2 days',
  142,
  8
),
(
  'The Future of AI in Education: Opportunities and Challenges',
  'future-ai-education',
  'Explore how artificial intelligence is transforming education and what it means for teachers and students.',
  '{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Artificial intelligence is revolutionizing the educational landscape, offering personalized learning experiences and automated assessment tools."}]}]}',
  '{"name": "Michael Chen", "bio": "EdTech specialist and AI researcher"}',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
  'https://images.unsplash.com/photo-1485827404703-89b55fcc595e',
  ARRAY['AI', 'EdTech', 'Future of Education'],
  ARRAY['artificial intelligence', 'education technology', 'future'],
  'The Future of AI in Education',
  'Discover how AI is transforming education and its implications for teachers',
  'Edu Tech',
  true,
  NOW() - INTERVAL '5 days',
  287,
  12
),
(
  'Creating Inclusive Classrooms: Best Practices',
  'creating-inclusive-classrooms',
  'Learn strategies to build a classroom environment where every student feels valued and supported.',
  '{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Inclusive education ensures that all students, regardless of their abilities or backgrounds, have equal opportunities to learn and succeed."}]}]}',
  '{"name": "Emily Rodriguez", "bio": "Special education expert"}',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
  'https://images.unsplash.com/photo-1503676260728-1c00da094a0b',
  ARRAY['Inclusion', 'Diversity', 'Best Practices'],
  ARRAY['inclusive education', 'classroom management', 'diversity'],
  'Creating Inclusive Classrooms',
  'Strategies for building inclusive classroom environments',
  'Case Study',
  true,
  NOW() - INTERVAL '1 week',
  412,
  10
),
(
  'Gamification in Education: Making Learning Fun',
  'gamification-education',
  'Discover how game-based learning can increase student engagement and improve learning outcomes.',
  '{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Gamification has emerged as a powerful tool in modern education, transforming traditional lessons into engaging, interactive experiences."}]}]}',
  '{"name": "David Kim", "bio": "Game-based learning specialist"}',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
  'https://images.unsplash.com/photo-1511512578047-dfb367046420',
  ARRAY['Gamification', 'Engagement', 'EdTech'],
  ARRAY['game-based learning', 'student engagement', 'educational games'],
  'Gamification in Education',
  'How game-based learning improves student engagement',
  'Tutorials',
  true,
  NOW() - INTERVAL '3 days',
  523,
  15
)
ON CONFLICT (slug) DO NOTHING;

-- Insert sample resources
INSERT INTO public.resources (
  title,
  description,
  url,
  type,
  subject,
  stage,
  tags,
  thumbnail_url,
  status,
  resource_type,
  grade_level,
  format,
  instructional_notes,
  is_active
) VALUES
(
  'Interactive Math Worksheets',
  'Collection of printable and interactive math worksheets for primary students',
  'https://example.com/math-worksheets',
  'Worksheet',
  'Math',
  'Primary',
  ARRAY['mathematics', 'worksheets', 'interactive'],
  'https://images.unsplash.com/photo-1509228468518-180dd4864904',
  'approved',
  'Worksheet',
  'Grade 3-5',
  'PDF',
  'Use these worksheets for daily practice or homework assignments',
  true
),
(
  'Science Experiment Videos',
  'Engaging video demonstrations of simple science experiments',
  'https://example.com/science-videos',
  'Video',
  'Science',
  'Secondary',
  ARRAY['science', 'experiments', 'videos'],
  'https://images.unsplash.com/photo-1532094349884-543bc11b234d',
  'approved',
  'Video',
  'Grade 6-8',
  'MP4',
  'Perfect for introducing new concepts or reviewing material',
  true
),
(
  'English Grammar Presentation',
  'Comprehensive PowerPoint presentation on English grammar rules',
  'https://example.com/grammar-ppt',
  'Presentation',
  'English',
  'Lower Secondary',
  ARRAY['english', 'grammar', 'presentation'],
  'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8',
  'approved',
  'Presentation',
  'Grade 7-9',
  'PPT',
  'Use for whole-class instruction or student self-study',
  true
),
(
  'History Timeline Interactive Tool',
  'Interactive web-based timeline for teaching historical events',
  'https://example.com/history-timeline',
  'Interactive',
  'Social Studies',
  'Upper Secondary',
  ARRAY['history', 'timeline', 'interactive'],
  'https://images.unsplash.com/photo-1481627834876-b7833e8f5570',
  'approved',
  'Interactive',
  'Grade 10-12',
  'Web',
  'Students can explore historical events chronologically',
  true
),
(
  'STEM Project Templates',
  'Ready-to-use templates for STEM projects and activities',
  'https://example.com/stem-templates',
  'Template',
  'STEM',
  'Primary',
  ARRAY['STEM', 'projects', 'templates'],
  'https://images.unsplash.com/photo-1581092160607-ee22e8d36c3e',
  'approved',
  'Template',
  'Grade 4-6',
  'DOCX',
  'Modify templates to suit your classroom needs',
  true
)
ON CONFLICT DO NOTHING;