// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvxruvyjlpnyyqtmbfnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2eHJ1dnlqbHBueXlxdG1iZm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzA3ODIsImV4cCI6MjA3Mjc0Njc4Mn0.T9ldOOkSYPrp2uJIBH5Ey1yIpLpdpBmswhGZyL_G9o4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});